### Register a new user
POST http://192.168.0.53:8080/register/
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "testpassword"
}

### Obtain JWT token
POST http://192.168.0.53:8080/login/
Content-Type: application/json

{
  "username": "tester1",
  "password": "applebanana123"
}

### Refresh JWT token
POST http://192.168.0.53:8080/token/refresh/
Content-Type: application/json

{
  "refresh": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoicmVmcmVzaCIsImV4cCI6MTc0MTg3NTUwNiwiaWF0IjoxNzQxNzg5MTA2LCJqdGkiOiJhMWNiZjQyMDJiZWI0ZDBlYmJhNmJkZWQ5MjUyMjNhNSIsInVzZXJfaWQiOjJ9.1D11TiuNdHeOcaD0-gtwxGZHvQFS-fxd7tTR4RiRyTQ"
}

### Access dashboard (requires authentication)
GET http://192.168.0.53:8080/dashboard/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxODczMjk3LCJpYXQiOjE3NDE4NzI5OTcsImp0aSI6ImE4YTc5YTM3OWI5YzQ2OGNhNmU1NTc4MjhhNWRiYTYwIiwidXNlcl9pZCI6M30._2wG8fv_huVOOuPl8T2n4KWzFpFGxIhXrVqXLei7yuA

### Create chat session
POST http://192.168.0.53:8080/chatbot/create_chat_session/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxODczNTU2LCJpYXQiOjE3NDE4NzMyNTYsImp0aSI6ImIwZDQyZDkxYmQ4YjQ1NWI5Zjg1YTBkYWY3MGU5NTMzIiwidXNlcl9pZCI6M30.KdzgoFzAVraqL_Ja--77UFwuK3iKsRxQjuBgbry-NsU

### Create chat message
POST http://192.168.0.53:8080/chatbot/create_chat_message/3/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxODczNTU2LCJpYXQiOjE3NDE4NzMyNTYsImp0aSI6ImIwZDQyZDkxYmQ4YjQ1NWI5Zjg1YTBkYWY3MGU5NTMzIiwidXNlcl9pZCI6M30.KdzgoFzAVraqL_Ja--77UFwuK3iKsRxQjuBgbry-NsU

{
  "sender": "user",
  "message": "Hello, this is a test message."
}

###
GET http://192.168.0.53:8080/health/health-metrics/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQxODc4OTQ1LCJpYXQiOjE3NDE4Nzg2NDUsImp0aSI6IjM5ZmI0MDY2ZTZmYzRhZDc5NzhkNGZiNzI0N2FjZjM0IiwidXNlcl9pZCI6MX0.qCjfyL9FhlBbm7glKdE3Pysn4nqPa7g2eFEDcsb7y_w

###
POST http://192.168.0.53:8080/health/lifestyle-planner/
Content-Type: application/json

{
  "avg_exercise_per_week": 3,
  "avg_sleep_hours": 7,
  "stress_level": 3,
  "diet_quality": "Good",
  "most_freq_substance_used": "Caffeine"
}