# Generated by Django 5.1.7 on 2025-03-13 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_exercise_per_week', models.IntegerField()),
                ('avg_sleep_hours', models.FloatField()),
                ('stress_level', models.IntegerField()),
                ('diet_quality', models.CharField(max_length=10)),
                ('most_freq_substance_used', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PredictedIllness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('predicted_disease', models.CharField(max_length=50)),
                ('confidence_score', models.FloatField()),
                ('risk_level', models.CharField(max_length=10)),
                ('health_metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictedillness', to='api.healthmetric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
